import type { LessonPlan, VisualPart } from "@/lib/lesson-schema";

const part = (value: Partial<VisualPart> & Pick<VisualPart, "type">): VisualPart => ({
  x: 0,
  y: 0,
  width: 0,
  height: 0,
  data: "",
  text: "",
  fill: "none",
  stroke: "ink",
  strokeWidth: 2,
  opacity: 1,
  ...value,
});

export function createDemoLesson(question = "How do neural networks learn?"): LessonPlan {
  const qLower = question.toLowerCase();

  // 1. Ocean Currents & Coriolis Circulation
  if (/\b(ocean|currents?|coriolis|thermohaline|gulf\s*stream|circulation)\b/i.test(qLower)) {
    return {
      id: `lesson-ocean-${Date.now()}`,
      title: "Why Ocean Currents Circulate",
      question,
      summary: "Solar equatorial heating, planetary Coriolis deflection, and deep thermohaline density gradients drive Earth's global ocean circulation conveyor.",
      diagramType: "cycle",
      visualStrategy: "A continuous oceanic pathway spanning equatorial thermal heating, Coriolis wind deflection, surface boundary gyres, and deep thermohaline overturning.",
      sources: [
        { id: "source-noaa", title: "Global Ocean Circulation & Thermohaline Conveyor", url: "https://www.noaa.gov/", publisher: "NOAA", summary: "Mechanisms of planetary wind-driven gyres and density-driven overturning circulation.", score: 0.98 },
      ],
      objects: [
        {
          id: "equatorial-heating",
          role: "input",
          shapeType: "custom",
          label: "Equatorial Solar Heating",
          labelPlacement: "above",
          x: 50,
          y: 130,
          width: 250,
          height: 380,
          parts: [
            part({ type: "ellipse", x: 45, y: 35, width: 140, height: 140, fill: "orange", stroke: "yellow", strokeWidth: 2.5, opacity: 1, text: "Direct Sunlight", data: "sun" }),
            part({ type: "particles", x: 25, y: 195, width: 195, height: 55, fill: "red", stroke: "orange", strokeWidth: 1.5, opacity: 0.9, text: "Thermal Water Expansion", data: "16" }),
            part({ type: "rect", x: 15, y: 270, width: 220, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Low-Latitude Thermal Input" }),
          ],
        },
        {
          id: "coriolis-deflection",
          role: "component",
          shapeType: "custom",
          label: "Coriolis Deflection & Trade Winds",
          labelPlacement: "above",
          x: 340,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "radial", x: 35, y: 40, width: 160, height: 160, fill: "none", stroke: "cyan", strokeWidth: 2, opacity: 0.85, data: "8" }),
            part({ type: "arrow", x: 30, y: 120, width: 160, height: -45, fill: "none", stroke: "cyan", strokeWidth: 3, opacity: 1, text: "Northern Rightward Drift", data: "coriolis" }),
            part({ type: "rect", x: 15, y: 230, width: 230, height: 42, fill: "slate", stroke: "cyan", strokeWidth: 1.5, opacity: 0.9, text: "Earth Spin Angular Momentum" }),
            part({ type: "rect", x: 15, y: 285, width: 230, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Hadley Atmospheric Wind Stress" }),
          ],
        },
        {
          id: "surface-gyres",
          role: "component",
          shapeType: "custom",
          label: "Surface Ocean Gyres & Gulf Stream",
          labelPlacement: "above",
          x: 640,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "orbit", x: 25, y: 35, width: 195, height: 170, fill: "none", stroke: "blue", strokeWidth: 2.5, opacity: 1, data: "gyre" }),
            part({ type: "arrow", x: 50, y: 150, width: 90, height: -90, fill: "none", stroke: "yellow", strokeWidth: 3, opacity: 1, text: "Gulf Stream Poleward Flow", data: "warm-current" }),
            part({ type: "rect", x: 15, y: 230, width: 230, height: 42, fill: "slate", stroke: "blue", strokeWidth: 1.5, opacity: 0.9, text: "Western Boundary Intensification" }),
            part({ type: "rect", x: 15, y: 285, width: 230, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Heat Transport to High Latitudes" }),
          ],
        },
        {
          id: "thermohaline-conveyor",
          role: "output",
          shapeType: "custom",
          label: "Deep Thermohaline Conveyor",
          labelPlacement: "above",
          x: 940,
          y: 130,
          width: 270,
          height: 380,
          parts: [
            part({ type: "arrow", x: 125, y: 35, width: 0, height: 130, fill: "none", stroke: "blue", strokeWidth: 4, opacity: 1, text: "Cold Saline Deep Sinking", data: "downwelling" }),
            part({ type: "particles", x: 25, y: 185, width: 220, height: 50, fill: "blue", stroke: "cyan", strokeWidth: 1.5, opacity: 0.95, text: "High Density Brine (4°C)", data: "18" }),
            part({ type: "rect", x: 15, y: 250, width: 240, height: 42, fill: "slate", stroke: "blue", strokeWidth: 1.5, opacity: 0.9, text: "North Atlantic Deep Water Formation" }),
            part({ type: "rect", x: 15, y: 305, width: 240, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Centuries-Long Global Overturning" }),
          ],
        },
      ],
      connections: [
        { id: "conn-heat-coriolis", from: "equatorial-heating", to: "coriolis-deflection", label: "wind pressure", color: "orange", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-coriolis-gyre", from: "coriolis-deflection", to: "surface-gyres", label: "trade winds", color: "cyan", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-gyre-thermo", from: "surface-gyres", to: "thermohaline-conveyor", label: "heat transport", color: "blue", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
      ],
      segments: [
        { id: "seg-ocean-1", title: "Equatorial Solar Heating", targetIds: ["equatorial-heating"], action: "reveal", durationMs: 7500, narration: "Circulation begins at the equator, where intense equatorial solar heating warms tropical surface waters, creating thermal water expansion." },
        { id: "seg-ocean-2", title: "Coriolis Deflection & Trade Winds", targetIds: ["coriolis-deflection"], action: "focus", durationMs: 8000, narration: "As these warm waters drift, Coriolis deflection and trade winds push currents to the right in the Northern Hemisphere due to Earth's planetary rotation." },
        { id: "seg-ocean-3", title: "Surface Ocean Gyres & Gulf Stream", targetIds: ["surface-gyres"], action: "trace", durationMs: 8000, narration: "This continuous deflection organizes massive surface ocean gyres and the Gulf Stream, transporting colossal quantities of warm water toward the polar regions." },
        { id: "seg-ocean-4", title: "Deep Thermohaline Conveyor", targetIds: ["thermohaline-conveyor"], action: "pulse", durationMs: 8500, narration: "In the North Atlantic, cooling and ice formation leave behind dense, salty brine, powering the deep thermohaline conveyor that sinks and circulates worldwide across centuries." },
      ],
    };
  }

  // 2. Aerodynamic Flight & Airfoil Wing Lift
  if (/\b(airplane|aerodynamic|airfoil|wing|bernoulli|flight|fly|lift)\b/i.test(qLower)) {
    return {
      id: `lesson-flight-${Date.now()}`,
      title: "How Airplane Wings Generate Lift",
      question,
      summary: "Asymmetrical camber accelerates airflow over the upper wing surface, creating a Bernoulli pressure differential and downward flow that generates upward lift.",
      diagramType: "cycle",
      visualStrategy: "An aerodynamic wind-tunnel section showing the cambered airfoil, differential velocity streamlines, net lift vector, and governing lift formulas.",
      sources: [
        { id: "source-nasa", title: "Aerodynamic Lift & Bernoulli Principles", url: "https://www.nasa.gov/", publisher: "NASA Glenn Research Center", summary: "Fluid dynamics of wing airfoils and pressure distribution.", score: 0.98 },
      ],
      objects: [
        {
          id: "airfoil-camber",
          role: "subject",
          shapeType: "custom",
          label: "Cambered Airfoil Profile",
          labelPlacement: "above",
          x: 50,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "path", data: "M 25 150 C 70 60 170 80 230 150 C 160 165 70 165 25 150 Z", fill: "slate", stroke: "cyan", strokeWidth: 2.5, opacity: 0.9, text: "" }),
            part({ type: "ellipse", x: 22, y: 142, width: 16, height: 16, fill: "yellow", stroke: "orange", strokeWidth: 1.5, opacity: 1, text: "Stagnation Pt" }),
            part({ type: "rect", x: 15, y: 220, width: 230, height: 42, fill: "slate", stroke: "cyan", strokeWidth: 1.5, opacity: 0.9, text: "Curved Upper Camber" }),
            part({ type: "rect", x: 15, y: 275, width: 230, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Flat Underside Contour" }),
          ],
        },
        {
          id: "streamline-flow",
          role: "component",
          shapeType: "custom",
          label: "Velocity & Pressure Field",
          labelPlacement: "above",
          x: 350,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "wave", x: 15, y: 55, width: 225, height: 28, fill: "none", stroke: "yellow", strokeWidth: 3, opacity: 1, text: "High Speed v_top", data: "4" }),
            part({ type: "rect", x: 45, y: 90, width: 165, height: 35, fill: "blue", stroke: "cyan", strokeWidth: 1.5, opacity: 0.45, text: "Low Pressure (P_low)" }),
            part({ type: "line", x: 15, y: 175, width: 225, height: 0, fill: "none", stroke: "slate", strokeWidth: 3, opacity: 0.8, text: "Lower Speed v_bottom" }),
            part({ type: "rect", x: 45, y: 190, width: 165, height: 35, fill: "orange", stroke: "yellow", strokeWidth: 1.5, opacity: 0.45, text: "High Pressure (P_high)" }),
            part({ type: "rect", x: 15, y: 265, width: 230, height: 45, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Bernoulli P + ½ρv² = Constant" }),
          ],
        },
        {
          id: "aerodynamic-lift",
          role: "output",
          shapeType: "custom",
          label: "Aerodynamic Lift & Downwash",
          labelPlacement: "above",
          x: 650,
          y: 130,
          width: 250,
          height: 380,
          parts: [
            part({ type: "arrow", x: 125, y: 180, width: 0, height: -125, fill: "none", stroke: "green", strokeWidth: 4.5, opacity: 1, text: "Net Aerodynamic Lift (L)", data: "lift" }),
            part({ type: "arrow", x: 160, y: 160, width: 65, height: 60, fill: "none", stroke: "cyan", strokeWidth: 3, opacity: 0.9, text: "Induced Downwash", data: "downwash" }),
            part({ type: "rect", x: 15, y: 245, width: 220, height: 42, fill: "slate", stroke: "green", strokeWidth: 1.5, opacity: 0.9, text: "Upward Normal Reaction" }),
            part({ type: "rect", x: 15, y: 300, width: 220, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Newton's Third Law Momentum" }),
          ],
        },
        {
          id: "lift-equation",
          role: "formula",
          shapeType: "custom",
          label: "Governing Lift Equations",
          labelPlacement: "above",
          x: 935,
          y: 130,
          width: 295,
          height: 380,
          parts: [
            part({ type: "rect", x: 12, y: 45, width: 270, height: 80, fill: "none", stroke: "cyan", strokeWidth: 1.5, opacity: 0.85 }),
            part({ type: "text", x: 147, y: 70, width: 250, height: 13, text: "Bernoulli Pressure Relation:", fill: "cyan" }),
            part({ type: "text", x: 147, y: 98, width: 250, height: 16, text: "ΔP = ½ ρ ( v_top² - v_bottom² )", fill: "white" }),
            part({ type: "rect", x: 12, y: 145, width: 270, height: 110, fill: "none", stroke: "green", strokeWidth: 1.5, opacity: 0.85 }),
            part({ type: "text", x: 147, y: 172, width: 250, height: 14, text: "Total Aerodynamic Lift:", fill: "yellow" }),
            part({ type: "text", x: 147, y: 204, width: 250, height: 18, text: "L = ½ · C_L · ρ · v² · S", fill: "green" }),
            part({ type: "text", x: 147, y: 236, width: 250, height: 12, text: "ρ: density  ·  S: wing surface area", fill: "slate" }),
            part({ type: "text", x: 147, y: 285, width: 250, height: 12, text: "C_L: coefficient of lift", fill: "slate" }),
          ],
        },
      ],
      connections: [
        { id: "conn-camber-flow", from: "airfoil-camber", to: "streamline-flow", label: "splits airflow", color: "cyan", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-flow-lift", from: "streamline-flow", to: "aerodynamic-lift", label: "pressure ΔP", color: "green", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-lift-formula", from: "aerodynamic-lift", to: "lift-equation", label: "lift force", color: "yellow", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
      ],
      segments: [
        { id: "seg-flight-1", title: "Cambered Airfoil Profile", targetIds: ["airfoil-camber"], action: "reveal", durationMs: 7500, narration: "The wing's cross section is a cambered airfoil profile, engineered with an arched upper curve and flatter lower surface." },
        { id: "seg-flight-2", title: "Velocity & Pressure Field", targetIds: ["streamline-flow"], action: "focus", durationMs: 8000, narration: "Air accelerates over the curved top, creating a high velocity zone where the velocity and pressure field drops to create low static pressure." },
        { id: "seg-flight-3", title: "Aerodynamic Lift & Downwash", targetIds: ["aerodynamic-lift"], action: "trace", durationMs: 8000, narration: "Because pressure beneath the wing is higher, a powerful upward force creates aerodynamic lift while defecting air downward." },
        { id: "seg-flight-4", title: "Governing Lift Equations", targetIds: ["lift-equation"], action: "pulse", durationMs: 8500, narration: "The magnitude of total lift depends directly on air density rho, velocity squared, wing area S, and lift coefficient C L." },
      ],
    };
  }

  // 3. Four-Stroke Internal Combustion Engine
  if (/\b(engine|combustion|piston|cylinder|four\s*stroke|4\s*stroke|spark\s*plug)\b/i.test(qLower)) {
    return {
      id: `lesson-engine-${Date.now()}`,
      title: "How a 4-Stroke Engine Works",
      question,
      summary: "Chemical fuel energy transforms into rotational crankshaft torque through four sequential strokes: Intake, Compression, Power, and Exhaust.",
      diagramType: "cycle",
      visualStrategy: "A synchronized 4-stage thermodynamic combustion sequence from fuel-air intake, piston compression, spark ignition, to exhaust purge.",
      sources: [
        { id: "source-sae", title: "Internal Combustion Engine Principles", url: "https://www.sae.org/", publisher: "SAE International", summary: "Four-stroke Otto cycle mechanics and thermodynamics.", score: 0.97 },
      ],
      objects: [
        {
          id: "intake-stroke",
          role: "input",
          shapeType: "custom",
          label: "1. Intake Stroke",
          labelPlacement: "above",
          x: 50,
          y: 130,
          width: 250,
          height: 380,
          parts: [
            part({ type: "rect", x: 20, y: 30, width: 210, height: 180, fill: "none", stroke: "slate", strokeWidth: 2, opacity: 1, text: "" }),
            part({ type: "line", x: 45, y: 30, width: 35, height: 35, fill: "none", stroke: "cyan", strokeWidth: 3, opacity: 1, text: "Intake Valve Open" }),
            part({ type: "rect", x: 35, y: 130, width: 180, height: 45, fill: "slate", stroke: "white", strokeWidth: 2, opacity: 1, text: "Descending Piston" }),
            part({ type: "arrow", x: 125, y: 95, width: 0, height: 35, fill: "none", stroke: "cyan", strokeWidth: 3, opacity: 1, text: "Induction Vacuum", data: "flow" }),
            part({ type: "rect", x: 15, y: 240, width: 220, height: 45, fill: "slate", stroke: "cyan", strokeWidth: 1.5, opacity: 0.9, text: "Draws Air-Fuel Charge" }),
          ],
        },
        {
          id: "compression-stroke",
          role: "component",
          shapeType: "custom",
          label: "2. Compression Stroke",
          labelPlacement: "above",
          x: 340,
          y: 130,
          width: 250,
          height: 380,
          parts: [
            part({ type: "rect", x: 20, y: 30, width: 210, height: 180, fill: "none", stroke: "slate", strokeWidth: 2, opacity: 1, text: "" }),
            part({ type: "line", x: 45, y: 30, width: 35, height: 0, fill: "none", stroke: "ink", strokeWidth: 3, opacity: 1, text: "Valves Sealed" }),
            part({ type: "line", x: 170, y: 30, width: 35, height: 0, fill: "none", stroke: "ink", strokeWidth: 3, opacity: 1 }),
            part({ type: "rect", x: 35, y: 65, width: 180, height: 45, fill: "slate", stroke: "white", strokeWidth: 2, opacity: 1, text: "Rising Piston" }),
            part({ type: "particles", x: 35, y: 35, width: 180, height: 28, fill: "orange", stroke: "yellow", strokeWidth: 1.5, opacity: 0.95, text: "High Pressure (10:1 CR)", data: "18" }),
            part({ type: "rect", x: 15, y: 240, width: 220, height: 45, fill: "slate", stroke: "orange", strokeWidth: 1.5, opacity: 0.9, text: "Adiabatic Mixture Heating" }),
          ],
        },
        {
          id: "power-stroke",
          role: "component",
          shapeType: "custom",
          label: "3. Power & Combustion Stroke",
          labelPlacement: "above",
          x: 630,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "rect", x: 20, y: 30, width: 220, height: 180, fill: "none", stroke: "slate", strokeWidth: 2, opacity: 1, text: "" }),
            part({ type: "line", x: 130, y: 15, width: 0, height: 35, fill: "none", stroke: "yellow", strokeWidth: 3.5, opacity: 1, text: "Spark Plug Arc" }),
            part({ type: "wave", x: 35, y: 45, width: 190, height: 40, fill: "none", stroke: "yellow", strokeWidth: 3, opacity: 1, text: "Flame Front Ignition", data: "4" }),
            part({ type: "rect", x: 35, y: 120, width: 190, height: 45, fill: "red", stroke: "orange", strokeWidth: 2, opacity: 0.9, text: "High Downward Force" }),
            part({ type: "rect", x: 15, y: 240, width: 230, height: 45, fill: "slate", stroke: "red", strokeWidth: 1.5, opacity: 0.9, text: "Expansion Drives Crankshaft" }),
          ],
        },
        {
          id: "exhaust-stroke",
          role: "output",
          shapeType: "custom",
          label: "4. Exhaust Stroke",
          labelPlacement: "above",
          x: 930,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "rect", x: 20, y: 30, width: 220, height: 180, fill: "none", stroke: "slate", strokeWidth: 2, opacity: 1, text: "" }),
            part({ type: "line", x: 170, y: 30, width: 35, height: 35, fill: "none", stroke: "orange", strokeWidth: 3, opacity: 1, text: "Exhaust Valve Open" }),
            part({ type: "rect", x: 35, y: 70, width: 190, height: 45, fill: "slate", stroke: "white", strokeWidth: 2, opacity: 1, text: "Ascending Piston" }),
            part({ type: "arrow", x: 175, y: 70, width: 0, height: -45, fill: "none", stroke: "slate", strokeWidth: 3, opacity: 1, text: "Burnt Gas Evacuation", data: "exhaust" }),
            part({ type: "rect", x: 15, y: 240, width: 230, height: 45, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Purges Cylinder for Next Cycle" }),
          ],
        },
      ],
      connections: [
        { id: "conn-intake-comp", from: "intake-stroke", to: "compression-stroke", label: "rotates 180°", color: "cyan", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-comp-power", from: "compression-stroke", to: "power-stroke", label: "spark ignition", color: "yellow", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-power-exhaust", from: "power-stroke", to: "exhaust-stroke", label: "power stroke", color: "red", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
      ],
      segments: [
        { id: "seg-eng-1", title: "1. Intake Stroke", targetIds: ["intake-stroke"], action: "reveal", durationMs: 7500, narration: "During the first intake stroke, the intake valve opens as the piston descends, drawing a combustible fuel air mixture into the cylinder." },
        { id: "seg-eng-2", title: "2. Compression Stroke", targetIds: ["compression-stroke"], action: "focus", durationMs: 7500, narration: "Next, both valves seal tightly during the compression stroke as the rising piston compresses the charge, raising its pressure and temperature." },
        { id: "seg-eng-3", title: "3. Power & Combustion", targetIds: ["power-stroke"], action: "pulse", durationMs: 8000, narration: "At top dead center, the spark plug fires to trigger the power and combustion stroke, forcing the piston down with explosive expansion force." },
        { id: "seg-eng-4", title: "4. Exhaust Stroke", targetIds: ["exhaust-stroke"], action: "trace", durationMs: 7500, narration: "Finally, during the exhaust stroke, the exhaust valve opens and the ascending piston sweeps spent combustion gases out to reset the cycle." },
      ],
    };
  }

  // 4. CRISPR-Cas9 Targeted Gene Editing
  if (/\b(crispr|cas9|gene\s*edit|endonuclease|dna\s*cut)\b/i.test(qLower)) {
    return {
      id: `lesson-crispr-${Date.now()}`,
      title: "CRISPR-Cas9 Targeted Gene Editing",
      question,
      summary: "Cas9 endonuclease guided by RNA unzips genomic DNA at a PAM site to introduce a precise double-strand break.",
      diagramType: "cycle",
      visualStrategy: "A horizontal molecular pathway showing Cas9 endonuclease enzyme, guide RNA targeting, DNA double helix, and double-strand cleavage.",
      sources: [
        { id: "source-nature", title: "CRISPR-Cas9 Structures and Mechanisms", url: "https://www.nature.com/", publisher: "Nature", summary: "Structural biology of Cas9 endonuclease and gRNA hybridization.", score: 0.98 },
      ],
      objects: [
        {
          id: "cas9-enzyme",
          role: "subject",
          shapeType: "custom",
          label: "Cas9 Endonuclease Enzyme",
          labelPlacement: "above",
          x: 50,
          y: 130,
          width: 250,
          height: 380,
          parts: [
            part({ type: "polygon", data: "20,40 220,30 235,90 220,330 30,340 10,100", fill: "violet", stroke: "violet", strokeWidth: 2, opacity: 0.35, text: "" }),
            part({ type: "ellipse", x: 35, y: 70, width: 70, height: 70, fill: "violet", stroke: "white", strokeWidth: 1.5, opacity: 0.9, text: "REC Lobe" }),
            part({ type: "ellipse", x: 140, y: 85, width: 70, height: 70, fill: "blue", stroke: "cyan", strokeWidth: 1.5, opacity: 0.9, text: "NUC Lobe" }),
            part({ type: "rect", x: 25, y: 220, width: 200, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "HNH / RuvC Catalytic Domain" }),
          ],
        },
        {
          id: "guide-rna",
          role: "component",
          shapeType: "custom",
          label: "Single Guide RNA (sgRNA)",
          labelPlacement: "above",
          x: 340,
          y: 130,
          width: 250,
          height: 380,
          parts: [
            part({ type: "wave", x: 20, y: 80, width: 210, height: 45, fill: "none", stroke: "yellow", strokeWidth: 3.5, opacity: 1, text: "20-nt Spacer Sequence", data: "4" }),
            part({ type: "path", data: "M 190 95 C 230 50 230 180 190 135", fill: "none", stroke: "orange", strokeWidth: 3, opacity: 1, text: "Hairpin Loop" }),
            part({ type: "rect", x: 20, y: 220, width: 210, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "TracrRNA Scaffold Assembly" }),
          ],
        },
        {
          id: "target-dna",
          role: "component",
          shapeType: "custom",
          label: "Target DNA Double Helix",
          labelPlacement: "above",
          x: 630,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "line", x: 15, y: 80, width: 230, height: 0, fill: "none", stroke: "cyan", strokeWidth: 3.5, text: "Target DNA Strand (5' -> 3')" }),
            part({ type: "line", x: 15, y: 150, width: 230, height: 0, fill: "none", stroke: "blue", strokeWidth: 3.5, text: "Non-Target Strand (3' -> 5')" }),
            part({ type: "line", x: 50, y: 80, width: 0, height: 70, stroke: "ink", strokeWidth: 1.5, opacity: 0.8 }),
            part({ type: "line", x: 100, y: 80, width: 0, height: 70, stroke: "ink", strokeWidth: 1.5, opacity: 0.8 }),
            part({ type: "line", x: 150, y: 80, width: 0, height: 70, stroke: "ink", strokeWidth: 1.5, opacity: 0.8 }),
            part({ type: "rect", x: 175, y: 70, width: 75, height: 90, fill: "orange", stroke: "yellow", strokeWidth: 2, opacity: 0.45, text: "PAM (5'-NGG)" }),
          ],
        },
        {
          id: "cleavage-dsb",
          role: "output",
          shapeType: "custom",
          label: "Double-Strand Break (DSB)",
          labelPlacement: "above",
          x: 930,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "arrow", x: 130, y: 70, width: 0, height: 55, fill: "none", stroke: "red", strokeWidth: 3.5, text: "Cut 3-bp Upstream", data: "cut" }),
            part({ type: "rect", x: 20, y: 160, width: 220, height: 50, fill: "red", stroke: "orange", strokeWidth: 2, opacity: 0.4, text: "Blunt End Cleavage" }),
            part({ type: "rect", x: 20, y: 230, width: 220, height: 50, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Cellular Repair (NHEJ / HDR)" }),
          ],
        },
      ],
      connections: [
        { id: "conn-cas9-grna", from: "cas9-enzyme", to: "guide-rna", label: "loads sgRNA", color: "violet", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-grna-dna", from: "guide-rna", to: "target-dna", label: "hybridizes DNA", color: "yellow", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-dna-dsb", from: "target-dna", to: "cleavage-dsb", label: "cleaves DNA", color: "red", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
      ],
      segments: [
        { id: "seg-crispr-1", title: "Cas9 Endonuclease", targetIds: ["cas9-enzyme"], action: "reveal", durationMs: 7500, narration: "The CRISPR Cas9 system begins when the Cas9 endonuclease enzyme acts as molecular scissors to inspect and edit DNA." },
        { id: "seg-crispr-2", title: "Single Guide RNA", targetIds: ["guide-rna"], action: "focus", durationMs: 8000, narration: "A single guide RNA loads into Cas9, directing the enzyme using a complementary twenty nucleotide spacer sequence." },
        { id: "seg-crispr-3", title: "Target DNA Double Helix", targetIds: ["target-dna"], action: "trace", durationMs: 8000, narration: "Once bound, Cas9 unzips the target DNA double helix adjacent to a critical protospacer adjacent motif, or PAM site." },
        { id: "seg-crispr-4", title: "Double-Strand Break", targetIds: ["cleavage-dsb"], action: "pulse", durationMs: 8500, narration: "Finally, catalytic nuclease domains cleave both strands of DNA to create a precise double strand break, initiating gene knockout or insertion." },
      ],
    };
  }

  // 5. Hydraulic Braking System
  if (/\b(hydraulic|brake|braking|caliper|rotor|car\s*brake)\b/i.test(qLower)) {
    return {
      id: `lesson-brakes-${Date.now()}`,
      title: "How Hydraulic Braking Systems Work",
      question,
      summary: "Mechanical pedal effort drives a master cylinder, propagating hydraulic fluid pressure via Pascal's law to clamp brake calipers onto spinning disc rotors.",
      diagramType: "cycle",
      visualStrategy: "A continuous physical pipeline from the driver brake pedal lever, through the master cylinder, along the hydraulic line, to the wheel caliper and disc rotor.",
      sources: [
        { id: "source-auto", title: "Automotive Brake Systems Engineering", url: "https://www.sae.org/", publisher: "SAE", summary: "Principles of automotive hydraulics and disc brake dynamics.", score: 0.97 },
      ],
      objects: [
        {
          id: "brake-pedal",
          role: "input",
          shapeType: "custom",
          label: "Brake Pedal Lever",
          labelPlacement: "above",
          x: 50,
          y: 130,
          width: 240,
          height: 380,
          parts: [
            part({ type: "polygon", data: "25,15 45,15 35,140 15,140", fill: "slate", stroke: "ink", strokeWidth: 2, opacity: 1 }),
            part({ type: "ellipse", x: 25, y: 15, width: 22, height: 22, fill: "cyan", stroke: "blue", strokeWidth: 2, text: "Pivot Pin" }),
            part({ type: "rect", x: 8, y: 135, width: 55, height: 25, fill: "slate", stroke: "white", strokeWidth: 2, text: "Pedal Pad" }),
            part({ type: "arrow", x: 75, y: 145, width: -48, height: 0, fill: "none", stroke: "red", strokeWidth: 3, text: "Driver Effort (Fpedal)", data: "effort" }),
            part({ type: "arrow", x: 38, y: 80, width: 120, height: 0, fill: "none", stroke: "cyan", strokeWidth: 2.5, text: "Pushrod Force", data: "pushrod" }),
          ],
        },
        {
          id: "master-cylinder",
          role: "component",
          shapeType: "custom",
          label: "Master Cylinder & Reservoir",
          labelPlacement: "above",
          x: 330,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "rect", x: 20, y: 25, width: 100, height: 50, fill: "slate", stroke: "cyan", strokeWidth: 2, opacity: 0.85, text: "Brake Fluid Reservoir" }),
            part({ type: "rect", x: 20, y: 90, width: 220, height: 75, fill: "none", stroke: "ink", strokeWidth: 2, opacity: 1, text: "Bore Cylinder" }),
            part({ type: "rect", x: 25, y: 95, width: 50, height: 65, fill: "slate", stroke: "white", strokeWidth: 2, opacity: 1, text: "Piston" }),
            part({ type: "particles", x: 85, y: 98, width: 150, height: 60, fill: "cyan", stroke: "blue", strokeWidth: 1.5, opacity: 0.95, text: "Pascal's Pressure P = F/A", data: "18" }),
            part({ type: "rect", x: 20, y: 230, width: 220, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Dual Safety Split Circuits" }),
          ],
        },
        {
          id: "hydraulic-lines",
          role: "component",
          shapeType: "custom",
          label: "High-Pressure Brake Line",
          labelPlacement: "above",
          x: 630,
          y: 130,
          width: 250,
          height: 380,
          parts: [
            part({ type: "line", x: 10, y: 125, width: 230, height: 0, fill: "none", stroke: "cyan", strokeWidth: 6, opacity: 0.9, text: "Hydraulic Fluid Column" }),
            part({ type: "arrow", x: 30, y: 125, width: 180, height: 0, fill: "none", stroke: "yellow", strokeWidth: 3, opacity: 1, text: "Incompressible Fluid Flow", data: "flow" }),
            part({ type: "rect", x: 15, y: 200, width: 220, height: 50, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Steel-Braided Hose (2000 PSI)" }),
          ],
        },
        {
          id: "caliper-rotor",
          role: "output",
          shapeType: "custom",
          label: "Brake Caliper & Rotor",
          labelPlacement: "above",
          x: 920,
          y: 130,
          width: 280,
          height: 380,
          parts: [
            part({ type: "ellipse", x: 30, y: 35, width: 150, height: 150, fill: "slate", stroke: "white", strokeWidth: 2, opacity: 0.85, text: "Disc Rotor" }),
            part({ type: "ellipse", x: 80, y: 85, width: 50, height: 50, fill: "none", stroke: "slate", strokeWidth: 1.5, opacity: 0.9, text: "Hub" }),
            part({ type: "rect", x: 145, y: 55, width: 90, height: 110, fill: "red", stroke: "orange", strokeWidth: 2, opacity: 0.9, text: "Hydraulic Caliper" }),
            part({ type: "rect", x: 135, y: 75, width: 22, height: 70, fill: "orange", stroke: "yellow", strokeWidth: 1.5, opacity: 0.95, text: "Pads" }),
            part({ type: "arrow", x: 195, y: 110, width: -35, height: 0, fill: "none", stroke: "yellow", strokeWidth: 3, opacity: 1, text: "Friction Clamping Force", data: "clamping" }),
          ],
        },
      ],
      connections: [
        { id: "conn-pedal-cyl", from: "brake-pedal", to: "master-cylinder", label: "pushrod force", color: "cyan", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-cyl-line", from: "master-cylinder", to: "hydraulic-lines", label: "Pascal pressure", color: "yellow", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-line-caliper", from: "hydraulic-lines", to: "caliper-rotor", label: "clamp force", color: "red", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
      ],
      segments: [
        { id: "seg-brakes-1", title: "Brake Pedal Mechanism", targetIds: ["brake-pedal"], action: "reveal", durationMs: 7500, narration: "When you press the brake pedal, mechanical leverage multiplies the driver's foot force through a pivot into the pushrod." },
        { id: "seg-brakes-2", title: "Master Cylinder Compression", targetIds: ["master-cylinder"], action: "focus", durationMs: 8000, narration: "The pushrod drives a piston inside the master cylinder, compressing hydraulic fluid drawn from the reservoir." },
        { id: "seg-brakes-3", title: "Hydraulic Fluid Lines", targetIds: ["hydraulic-lines"], action: "flow", durationMs: 7500, narration: "Under Pascal's principle, pressure transmits undiminished through incompressible fluid columns across high pressure lines to each wheel." },
        { id: "seg-brakes-4", title: "Caliper and Disc Rotor", targetIds: ["caliper-rotor"], action: "pulse", durationMs: 8500, narration: "At the wheel, hydraulic caliper pistons clamp friction pads against the spinning disc rotor, converting kinetic energy into heat to stop the car." },
      ],
    };
  }

  // 6. Solar Eclipse Celestial Alignment
  if (/\b(eclipse|solar\s*eclipse|lunar\s*eclipse|umbra|penumbra)\b/i.test(qLower)) {
    return {
      id: `lesson-eclipse-${Date.now()}`,
      title: "How Solar Eclipses Occur",
      question,
      summary: "When the Moon passes directly between the Sun and Earth, its central umbral shadow cone traces a narrow path of totality across Earth's surface.",
      diagramType: "spatial",
      visualStrategy: "A linear astronomical alignment of Sun, Moon, and Earth showing the convergent umbra shadow cone, divergent penumbra, and observer totality zone.",
      sources: [
        { id: "source-astronomy", title: "Celestial Mechanics of Solar Eclipses", url: "https://eclipse.gsfc.nasa.gov/", publisher: "NASA Solar System Exploration", summary: "Geometry of syzygy, umbral cones, and path of totality.", score: 0.98 },
      ],
      objects: [
        {
          id: "eclipse-sun",
          role: "subject",
          shapeType: "custom",
          label: "The Sun",
          labelPlacement: "above",
          x: 50,
          y: 130,
          width: 250,
          height: 380,
          parts: [
            part({ type: "ellipse", x: 45, y: 55, width: 155, height: 155, fill: "orange", stroke: "yellow", strokeWidth: 3, opacity: 1, text: "Sun", data: "sun" }),
            part({ type: "wave", x: 25, y: 235, width: 195, height: 35, fill: "none", stroke: "yellow", strokeWidth: 2.5, opacity: 0.9, text: "Collimated Light Rays", data: "4" }),
            part({ type: "rect", x: 15, y: 290, width: 220, height: 42, fill: "slate", stroke: "yellow", strokeWidth: 1.5, opacity: 0.9, text: "Nuclear Fusion Radiation Source" }),
          ],
        },
        {
          id: "eclipse-moon",
          role: "component",
          shapeType: "custom",
          label: "The Moon (Syzygy Node)",
          labelPlacement: "above",
          x: 340,
          y: 130,
          width: 250,
          height: 380,
          parts: [
            part({ type: "ellipse", x: 80, y: 90, width: 90, height: 90, fill: "slate", stroke: "white", strokeWidth: 2, opacity: 1, text: "Moon", data: "moon" }),
            part({ type: "orbit", x: 25, y: 35, width: 200, height: 200, fill: "none", stroke: "slate", strokeWidth: 1.5, opacity: 0.6, data: "orbit" }),
            part({ type: "rect", x: 15, y: 250, width: 220, height: 42, fill: "slate", stroke: "white", strokeWidth: 1.5, opacity: 0.9, text: "Orbital Plane Intersection" }),
            part({ type: "rect", x: 15, y: 305, width: 220, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Apparent Angular Diameter = 0.5°" }),
          ],
        },
        {
          id: "shadow-cones",
          role: "component",
          shapeType: "custom",
          label: "Umbra & Penumbra Cones",
          labelPlacement: "above",
          x: 630,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "polygon", data: "20,60 220,110 220,150 20,200", fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.35, text: "" }),
            part({ type: "polygon", data: "20,105 220,125 220,135 20,155", fill: "slate", stroke: "ink", strokeWidth: 2, opacity: 0.75, text: "" }),
            part({ type: "line", x: 20, y: 130, width: 200, height: 0, fill: "none", stroke: "red", strokeWidth: 2.5, opacity: 0.9, text: "Central Umbra Cone" }),
            part({ type: "rect", x: 15, y: 250, width: 230, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Total Sun Occlusion (Umbra)" }),
            part({ type: "rect", x: 15, y: 305, width: 230, height: 42, fill: "slate", stroke: "slate", strokeWidth: 1.5, opacity: 0.9, text: "Partial Sun Obscuration (Penumbra)" }),
          ],
        },
        {
          id: "eclipse-earth",
          role: "output",
          shapeType: "custom",
          label: "Earth & Totality Zone",
          labelPlacement: "above",
          x: 930,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "ellipse", x: 45, y: 55, width: 165, height: 165, fill: "blue", stroke: "cyan", strokeWidth: 2.5, opacity: 1, text: "Earth", data: "earth" }),
            part({ type: "ellipse", x: 118, y: 130, width: 18, height: 18, fill: "ink", stroke: "yellow", strokeWidth: 2, opacity: 1, text: "Totality" }),
            part({ type: "rect", x: 15, y: 250, width: 230, height: 42, fill: "slate", stroke: "cyan", strokeWidth: 1.5, opacity: 0.9, text: "160km Wide Path of Totality" }),
            part({ type: "rect", x: 15, y: 305, width: 230, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Solar Corona Unveiled" }),
          ],
        },
      ],
      connections: [
        { id: "conn-sun-moon", from: "eclipse-sun", to: "eclipse-moon", label: "sunlight rays", color: "yellow", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-moon-cone", from: "eclipse-moon", to: "shadow-cones", label: "shadow cones", color: "slate", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-cone-earth", from: "shadow-cones", to: "eclipse-earth", label: "totality zone", color: "cyan", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
      ],
      segments: [
        { id: "seg-ecl-1", title: "The Sun Light Source", targetIds: ["eclipse-sun"], action: "reveal", durationMs: 7500, narration: "A solar eclipse starts with the Sun, emitting radiant parallel sunlight rays across millions of kilometers of empty space." },
        { id: "seg-ecl-2", title: "The Moon Alignment", targetIds: ["eclipse-moon"], action: "focus", durationMs: 8000, narration: "During a new moon, when orbits align at an orbital node, the Moon passes directly between the Sun and our home planet." },
        { id: "seg-ecl-3", title: "Umbra & Penumbra Cones", targetIds: ["shadow-cones"], action: "trace", durationMs: 8000, narration: "The Moon casts two distinct shadow cones: a dark central umbra cone where sunlight is fully blocked, surrounded by a wider penumbra." },
        { id: "seg-ecl-4", title: "Earth & Totality Zone", targetIds: ["eclipse-earth"], action: "pulse", durationMs: 8500, narration: "Where the umbral tip sweeps across Earth, observers experience daytime darkness and glimpse the radiant solar corona during totality." },
      ],
    };
  }

  // 7. Photosynthesis & Cellular Energy
  if (/\b(photosynthesis|chloroplast|thylakoid|calvin\s*cycle|light\s*reactions?|plants?.*cells?|sunlight.*energy|convert.*sunlight)\b/i.test(qLower)) {
    return {
      id: `lesson-photo-${Date.now()}`,
      title: "How Photosynthesis Converts Light to Food",
      question,
      summary: "Plants capture solar photons in thylakoid membranes to generate ATP and NADPH, which then fuel the Calvin cycle to convert CO2 into glucose sugars.",
      diagramType: "cycle",
      visualStrategy: "A biochemical factory flow showing chlorophyll photon capture, thylakoid water splitting, electron transport, and enzymatic Calvin cycle carbon fixation.",
      sources: [
        { id: "source-bio", title: "Molecular Biology of Photosynthesis", url: "https://www.nature.com/", publisher: "Nature Education", summary: "Z-scheme electron transport and Calvin cycle biochemistry.", score: 0.98 },
      ],
      objects: [
        {
          id: "photon-capture",
          role: "input",
          shapeType: "custom",
          label: "Solar Photon Absorption",
          labelPlacement: "above",
          x: 50,
          y: 130,
          width: 250,
          height: 380,
          parts: [
            part({ type: "ellipse", x: 45, y: 35, width: 140, height: 140, fill: "orange", stroke: "yellow", strokeWidth: 2.5, opacity: 1, text: "Sunlight (hν)", data: "sun" }),
            part({ type: "wave", x: 25, y: 195, width: 195, height: 35, fill: "none", stroke: "yellow", strokeWidth: 3, opacity: 1, text: "680 nm Wavelength", data: "4" }),
            part({ type: "rect", x: 15, y: 250, width: 220, height: 42, fill: "green", stroke: "ink", strokeWidth: 1.5, opacity: 0.8, text: "Chlorophyll a / b Pigments" }),
            part({ type: "rect", x: 15, y: 305, width: 220, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Antenna Complex Resonance" }),
          ],
        },
        {
          id: "thylakoid-reactions",
          role: "component",
          shapeType: "custom",
          label: "Thylakoid Light Reactions",
          labelPlacement: "above",
          x: 340,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "rect", x: 20, y: 40, width: 220, height: 150, fill: "green", stroke: "green", strokeWidth: 2, opacity: 0.25 }),
            part({ type: "rect", x: 35, y: 55, width: 190, height: 40, fill: "green", stroke: "ink", strokeWidth: 2, opacity: 0.9, text: "Photosystem II (H₂O -> O₂)" }),
            part({ type: "particles", x: 35, y: 110, width: 190, height: 35, fill: "cyan", stroke: "blue", strokeWidth: 1.5, opacity: 0.95, text: "Proton Gradient (H+)", data: "16" }),
            part({ type: "rect", x: 15, y: 230, width: 230, height: 42, fill: "slate", stroke: "cyan", strokeWidth: 1.5, opacity: 0.9, text: "Photolysis: Water Splitting" }),
            part({ type: "rect", x: 15, y: 285, width: 230, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Electron Transport Chain" }),
          ],
        },
        {
          id: "energy-carriers",
          role: "component",
          shapeType: "custom",
          label: "Energy Carriers: ATP & NADPH",
          labelPlacement: "above",
          x: 640,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "rect", x: 30, y: 45, width: 200, height: 60, fill: "yellow", stroke: "orange", strokeWidth: 2, opacity: 0.85, text: "ATP (Cellular Battery)" }),
            part({ type: "rect", x: 30, y: 125, width: 200, height: 60, fill: "cyan", stroke: "blue", strokeWidth: 2, opacity: 0.85, text: "NADPH (Reducing Power)" }),
            part({ type: "rect", x: 15, y: 230, width: 230, height: 42, fill: "slate", stroke: "yellow", strokeWidth: 1.5, opacity: 0.9, text: "Chemical Energy Storage" }),
            part({ type: "rect", x: 15, y: 285, width: 230, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Fuels Stroma Calvin Cycle" }),
          ],
        },
        {
          id: "calvin-cycle-sugars",
          role: "output",
          shapeType: "custom",
          label: "Calvin Cycle & Glucose",
          labelPlacement: "above",
          x: 940,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "orbit", x: 30, y: 35, width: 195, height: 170, fill: "none", stroke: "green", strokeWidth: 2.5, opacity: 0.9, data: "cycle" }),
            part({ type: "rect", x: 50, y: 95, width: 155, height: 45, fill: "green", stroke: "white", strokeWidth: 2, opacity: 0.95, text: "Glucose C₆H₁₂O₆" }),
            part({ type: "rect", x: 15, y: 230, width: 230, height: 42, fill: "slate", stroke: "green", strokeWidth: 1.5, opacity: 0.9, text: "Rubisco Carbon Fixation" }),
            part({ type: "rect", x: 15, y: 285, width: 230, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "CO₂ Converted to Biomass" }),
          ],
        },
      ],
      connections: [
        { id: "conn-photon-thylakoid", from: "photon-capture", to: "thylakoid-reactions", label: "excites chlorophyll", color: "yellow", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-thylakoid-atp", from: "thylakoid-reactions", to: "energy-carriers", label: "charges ATP & NADPH", color: "cyan", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-atp-calvin", from: "energy-carriers", to: "calvin-cycle-sugars", label: "powers carbon fixation", color: "green", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
      ],
      segments: [
        { id: "seg-photo-1", title: "Solar Photon Absorption", targetIds: ["photon-capture"], action: "reveal", durationMs: 7500, narration: "Photosynthesis begins with solar photon absorption, where chlorophyll pigments inside chloroplasts capture sunlight energy." },
        { id: "seg-photo-2", title: "Thylakoid Light Reactions", targetIds: ["thylakoid-reactions"], action: "focus", durationMs: 8000, narration: "Inside thylakoid light reactions, absorbed light splits water molecules into oxygen, releasing electrons and establishing a proton gradient." },
        { id: "seg-photo-3", title: "Energy Carriers: ATP & NADPH", targetIds: ["energy-carriers"], action: "flow", durationMs: 7500, narration: "This flow charges energy carriers ATP and NADPH, temporarily storing high-energy chemical bonds to power biosynthetic work." },
        { id: "seg-photo-4", title: "Calvin Cycle & Glucose", targetIds: ["calvin-cycle-sugars"], action: "pulse", durationMs: 8500, narration: "Finally, in the Calvin cycle, the enzyme Rubisco fixes carbon dioxide from the air into stable glucose sugars that feed plant growth." },
      ],
    };
  }

  // 8. Quantum Superposition & Bloch Sphere
  if (/\b(quantum|qubit|superposition|entangle|bloch\s*sphere|wavefunction)\b/i.test(qLower)) {
    return {
      id: `lesson-quantum-${Date.now()}`,
      title: "How Quantum Superposition Works",
      question,
      summary: "Unlike classical bits, a quantum bit exists in a continuous linear combination of states |0> and |1> on the Bloch sphere until measured.",
      diagramType: "mechanism",
      visualStrategy: "A quantum circuit and state progression from classical base states, Bloch sphere superposition vector, Hadamard phase rotation, to probabilistic measurement.",
      sources: [
        { id: "source-ibm", title: "Quantum Information & Superposition", url: "https://www.ibm.com/quantum", publisher: "IBM Quantum", summary: "Principles of quantum computation, Bloch spheres, and state evolution.", score: 0.98 },
      ],
      objects: [
        {
          id: "classical-vs-qubit",
          role: "input",
          shapeType: "custom",
          label: "Classical Bit vs Qubit",
          labelPlacement: "above",
          x: 50,
          y: 130,
          width: 250,
          height: 380,
          parts: [
            part({ type: "rect", x: 25, y: 35, width: 90, height: 60, fill: "slate", stroke: "white", strokeWidth: 2, opacity: 0.9, text: "Bit = 0" }),
            part({ type: "rect", x: 135, y: 35, width: 90, height: 60, fill: "slate", stroke: "white", strokeWidth: 2, opacity: 0.9, text: "Bit = 1" }),
            part({ type: "rect", x: 25, y: 120, width: 200, height: 80, fill: "cyan", stroke: "blue", strokeWidth: 2, opacity: 0.35, text: "|ψ⟩ = α|0⟩ + β|1⟩" }),
            part({ type: "rect", x: 15, y: 250, width: 220, height: 42, fill: "slate", stroke: "cyan", strokeWidth: 1.5, opacity: 0.9, text: "Two-State Quantum System" }),
            part({ type: "rect", x: 15, y: 305, width: 220, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Complex Probability Amplitudes" }),
          ],
        },
        {
          id: "bloch-sphere-state",
          role: "component",
          shapeType: "custom",
          label: "Bloch Sphere Representation",
          labelPlacement: "above",
          x: 340,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "ellipse", x: 45, y: 35, width: 170, height: 170, fill: "none", stroke: "cyan", strokeWidth: 2, opacity: 0.8 }),
            part({ type: "ellipse", x: 45, y: 85, width: 170, height: 70, fill: "none", stroke: "slate", strokeWidth: 1.5, opacity: 0.6 }),
            part({ type: "arrow", x: 130, y: 120, width: 50, height: -55, fill: "none", stroke: "yellow", strokeWidth: 3, opacity: 1, text: "State Vector |ψ⟩", data: "vector" }),
            part({ type: "text", x: 130, y: 25, width: 40, height: 14, text: "|0⟩ (North)", fill: "white" }),
            part({ type: "text", x: 130, y: 215, width: 40, height: 14, text: "|1⟩ (South)", fill: "white" }),
            part({ type: "rect", x: 15, y: 260, width: 230, height: 42, fill: "slate", stroke: "yellow", strokeWidth: 1.5, opacity: 0.9, text: "Unit Sphere in Hilbert Space" }),
          ],
        },
        {
          id: "hadamard-transformation",
          role: "component",
          shapeType: "custom",
          label: "Hadamard Superposition Gate",
          labelPlacement: "above",
          x: 640,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "rect", x: 35, y: 50, width: 190, height: 80, fill: "violet", stroke: "white", strokeWidth: 2.5, opacity: 0.9, text: "H-Gate [ 1  1 ; 1 -1 ]" }),
            part({ type: "wave", x: 30, y: 155, width: 200, height: 35, fill: "none", stroke: "cyan", strokeWidth: 3, opacity: 1, text: "Equator Superposition |+⟩", data: "3" }),
            part({ type: "rect", x: 15, y: 240, width: 230, height: 42, fill: "slate", stroke: "violet", strokeWidth: 1.5, opacity: 0.9, text: "50% Probability |0⟩ + 50% |1⟩" }),
            part({ type: "rect", x: 15, y: 295, width: 230, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Rotates Basis by 90 Degrees" }),
          ],
        },
        {
          id: "measurement-born-rule",
          role: "output",
          shapeType: "custom",
          label: "Measurement & Wavefunction Collapse",
          labelPlacement: "above",
          x: 940,
          y: 130,
          width: 270,
          height: 380,
          parts: [
            part({ type: "arrow", x: 135, y: 60, width: 0, height: 80, fill: "none", stroke: "red", strokeWidth: 4, opacity: 1, text: "Wavefunction Collapse", data: "collapse" }),
            part({ type: "rect", x: 25, y: 160, width: 220, height: 50, fill: "slate", stroke: "red", strokeWidth: 2, opacity: 0.85, text: "Born Rule: P(0) = |α|²" }),
            part({ type: "rect", x: 15, y: 240, width: 240, height: 42, fill: "slate", stroke: "red", strokeWidth: 1.5, opacity: 0.9, text: "Irreversible State Reduction" }),
            part({ type: "rect", x: 15, y: 295, width: 240, height: 42, fill: "slate", stroke: "ink", strokeWidth: 1.5, opacity: 0.9, text: "Yields Classical 0 or 1 Bit" }),
          ],
        },
      ],
      connections: [
        { id: "conn-qubit-bloch", from: "classical-vs-qubit", to: "bloch-sphere-state", label: "unit sphere", color: "cyan", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-bloch-hadamard", from: "bloch-sphere-state", to: "hadamard-transformation", label: "H-Gate rotate", color: "violet", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-hadamard-measure", from: "hadamard-transformation", to: "measurement-born-rule", label: "Born collapse", color: "red", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
      ],
      segments: [
        { id: "seg-quant-1", title: "Classical Bit vs Qubit", targetIds: ["classical-vs-qubit"], action: "reveal", durationMs: 7500, narration: "While classical computers store bits as definite zeroes or ones, a qubit exists in a continuous linear superposition of both states." },
        { id: "seg-quant-2", title: "Bloch Sphere Representation", targetIds: ["bloch-sphere-state"], action: "focus", durationMs: 8000, narration: "We visualize this on the Bloch sphere, where the north and south poles represent pure states, and any surface point is a valid superposition." },
        { id: "seg-quant-3", title: "Hadamard Superposition Gate", targetIds: ["hadamard-transformation"], action: "flow", durationMs: 7500, narration: "Applying a Hadamard superposition gate rotates the qubit onto the equator, creating an equal fifty fifty probability of measuring zero or one." },
        { id: "seg-quant-4", title: "Measurement & Wavefunction Collapse", targetIds: ["measurement-born-rule"], action: "pulse", durationMs: 8500, narration: "Upon measurement, the delicate superposition experiences wavefunction collapse under the Born rule, instantly projecting into a single classical bit." },
      ],
    };
  }

  // 8. Tokamak Nuclear Fusion Plasma Confinement
  if (/\b(fusion|tokamak|iter|plasma|magnetic\s*confinement|solenoid|deuterium|tritium|nuclear\s*fusion)\b/i.test(qLower)) {
    return {
      id: `lesson-fusion-${Date.now()}`,
      title: "How Tokamak Reactors Confine Fusion Plasma",
      question,
      summary: "Powerful superconducting magnetic coils generate helical magnetic fields to confine 150-million-degree hydrogen plasma away from reactor walls to achieve net nuclear fusion energy.",
      diagramType: "cycle",
      visualStrategy: "A cutaway cross-section of a Tokamak magnetic cage showing the central solenoid, D-shaped toroidal field coils, helical plasma core, and bottom divertor.",
      sources: [
        { id: "source-iter", title: "ITER: The Way to New Energy & Tokamak Physics", url: "https://www.iter.org/", publisher: "ITER Organization", summary: "Superconducting magnetic confinement principles and fusion plasma physics.", score: 0.99 },
      ],
      objects: [
        {
          id: "central-solenoid",
          role: "input",
          shapeType: "custom",
          label: "Central Solenoid & Coils",
          labelPlacement: "above",
          x: 50,
          y: 130,
          width: 230,
          height: 380,
          parts: [
            part({ type: "rect", x: 45, y: 30, width: 140, height: 260, fill: "none", stroke: "blue", strokeWidth: 3, opacity: 0.9, text: "Solenoid Backbone" }),
            part({ type: "coil", x: 55, y: 45, width: 120, height: 230, fill: "none", stroke: "cyan", strokeWidth: 2.8, opacity: 1, data: "8" }),
            part({ type: "rect", x: 15, y: 310, width: 200, height: 44, fill: "slate", stroke: "ink", strokeWidth: 1.5, text: "Pulsed Current: 40 MA" }),
          ],
        },
        {
          id: "toroidal-magnets",
          role: "component",
          shapeType: "custom",
          label: "Toroidal Field Magnets",
          labelPlacement: "above",
          x: 410,
          y: 130,
          width: 240,
          height: 380,
          parts: [
            part({ type: "rect", x: 25, y: 25, width: 190, height: 270, fill: "none", stroke: "violet", strokeWidth: 4, opacity: 0.95, text: "D-Shaped Coil" }),
            part({ type: "rect", x: 45, y: 45, width: 150, height: 230, fill: "none", stroke: "violet", strokeWidth: 1.8, opacity: 0.7 }),
            part({ type: "rect", x: 10, y: 310, width: 220, height: 44, fill: "slate", stroke: "ink", strokeWidth: 1.5, text: "Magnetic Field: 11.8 Tesla" }),
          ],
        },
        {
          id: "plasma-torus",
          role: "output",
          shapeType: "custom",
          label: "Confined Fusion Plasma",
          labelPlacement: "above",
          x: 780,
          y: 130,
          width: 260,
          height: 380,
          parts: [
            part({ type: "ellipse", x: 20, y: 40, width: 220, height: 240, fill: "orange", stroke: "yellow", strokeWidth: 3, opacity: 0.45, text: "150,000,000 °C Core" }),
            part({ type: "particles", x: 40, y: 65, width: 180, height: 190, fill: "cyan", stroke: "white", strokeWidth: 1.5, opacity: 0.95, text: "D-T Ions", data: "24" }),
            part({ type: "wave", x: 35, y: 145, width: 190, height: 36, fill: "none", stroke: "yellow", strokeWidth: 3, opacity: 0.9, data: "4" }),
            part({ type: "rect", x: 15, y: 310, width: 230, height: 44, fill: "slate", stroke: "ink", strokeWidth: 1.5, text: "Helical Magnetic Twist" }),
          ],
        },
        {
          id: "divertor-vessel",
          role: "output",
          shapeType: "custom",
          label: "Divertor & Vacuum Vessel",
          labelPlacement: "above",
          x: 1170,
          y: 130,
          width: 290,
          height: 380,
          parts: [
            part({ type: "rect", x: 15, y: 25, width: 260, height: 270, fill: "none", stroke: "slate", strokeWidth: 3.5, opacity: 0.85, text: "Vacuum Cryostat" }),
            part({ type: "rect", x: 25, y: 230, width: 240, height: 55, fill: "red", stroke: "orange", strokeWidth: 2, opacity: 0.7, text: "Tungsten Divertor (Heat Exhaust)" }),
            part({ type: "line", x: 35, y: 70, width: 220, height: 0, stroke: "cyan", strokeWidth: 2, opacity: 0.6 }),
            part({ type: "rect", x: 10, y: 310, width: 270, height: 44, fill: "slate", stroke: "ink", strokeWidth: 1.5, text: "Helium Ash Extraction: 10 MW/m²" }),
          ],
        },
      ],
      connections: [
        { id: "conn-solenoid-coils", from: "central-solenoid", to: "toroidal-magnets", label: "induces current", color: "blue", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-coils-plasma", from: "toroidal-magnets", to: "plasma-torus", label: "confines plasma", color: "violet", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
        { id: "conn-plasma-divertor", from: "plasma-torus", to: "divertor-vessel", label: "exhausts heat", color: "red", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
      ],
      segments: [
        { id: "seg-fuse-1", title: "Central Solenoid & Coils", targetIds: ["central-solenoid"], action: "reveal", durationMs: 7500, narration: "The central solenoid acts as a giant transformer electromagnet, pulsing millions of amperes to induce a powerful electric current directly through the fuel gas." },
        { id: "seg-fuse-2", title: "Toroidal Field Magnets", targetIds: ["toroidal-magnets"], action: "focus", durationMs: 8000, narration: "D-shaped toroidal field magnets encircle the chamber, creating a massive magnetic cage that forces charged ions into closed helical trajectories." },
        { id: "seg-fuse-3", title: "Confined Fusion Plasma", targetIds: ["plasma-torus"], action: "flow", durationMs: 8500, narration: "Inside this magnetic bottle, the confined deuterium-tritium plasma reaches one hundred fifty million degrees Celsius, hot enough for atomic nuclei to overcome repulsion and fuse." },
        { id: "seg-fuse-4", title: "Divertor & Vacuum Vessel", targetIds: ["divertor-vessel"], action: "pulse", durationMs: 8500, narration: "At the chamber base, the tungsten divertor extracts helium fusion ash while tolerating extreme surface heat loads exceeding ten megawatts per square meter." },
      ],
    };
  }

  // 9. Neural Network Learning (Default fallback or explicit match)
  return {
    id: `lesson-nn-${Date.now()}`,
    title: question.replace(/[?.!]+$/, "").slice(0, 82),
    question,
    summary: "At each layer, features are weighted and transformed, then loss feedback computes gradients to tune network weights.",
    diagramType: "cycle",
    visualStrategy: "A canonical layered neural network with input, hidden, and output stages, connected directly to governing learning equations.",
    sources: [
      { id: "source-mit", title: "Introduction to Deep Learning", url: "https://introtodeeplearning.com/", publisher: "MIT", summary: "Core concepts behind training neural networks.", score: 0.97 },
    ],
    objects: [
      {
        id: "nn-input-layer",
        role: "input",
        shapeType: "custom",
        label: "Input Layer (X)",
        labelPlacement: "above",
        x: 60,
        y: 130,
        width: 190,
        height: 380,
        parts: [
          part({ type: "ellipse", x: 45, y: 60, width: 60, height: 60, fill: "blue", stroke: "cyan", strokeWidth: 2.5, text: "x₁", data: "circle" }),
          part({ type: "ellipse", x: 45, y: 145, width: 60, height: 60, fill: "blue", stroke: "cyan", strokeWidth: 2.5, text: "x₂", data: "circle" }),
          part({ type: "ellipse", x: 45, y: 230, width: 60, height: 60, fill: "blue", stroke: "cyan", strokeWidth: 2.5, text: "x₃", data: "circle" }),
        ],
      },
      {
        id: "nn-hidden-layer",
        role: "component",
        shapeType: "custom",
        label: "Hidden Layer (H)",
        labelPlacement: "above",
        x: 310,
        y: 130,
        width: 210,
        height: 380,
        parts: [
          part({ type: "ellipse", x: 50, y: 45, width: 56, height: 56, fill: "violet", stroke: "violet", strokeWidth: 2.5, text: "h₁", data: "circle" }),
          part({ type: "ellipse", x: 50, y: 115, width: 56, height: 56, fill: "violet", stroke: "violet", strokeWidth: 2.5, text: "h₂", data: "circle" }),
          part({ type: "ellipse", x: 50, y: 185, width: 56, height: 56, fill: "violet", stroke: "violet", strokeWidth: 2.5, text: "h₃", data: "circle" }),
          part({ type: "ellipse", x: 50, y: 255, width: 56, height: 56, fill: "violet", stroke: "violet", strokeWidth: 2.5, text: "h₄", data: "circle" }),
        ],
      },
      {
        id: "nn-output-layer",
        role: "output",
        shapeType: "custom",
        label: "Output Layer (Ŷ)",
        labelPlacement: "above",
        x: 580,
        y: 130,
        width: 190,
        height: 380,
        parts: [
          part({ type: "ellipse", x: 45, y: 145, width: 64, height: 64, fill: "green", stroke: "green", strokeWidth: 2.5, text: "ŷ", data: "circle" }),
        ],
      },
      {
        id: "nn-formula-loss",
        role: "formula",
        shapeType: "custom",
        label: "Governing Learning Equations",
        labelPlacement: "above",
        x: 840,
        y: 130,
        width: 330,
        height: 380,
        parts: [
          part({ type: "rect", x: 12, y: 45, width: 306, height: 75, fill: "none", stroke: "blue", strokeWidth: 1.5, opacity: 0.85 }),
          part({ type: "text", x: 165, y: 68, width: 280, height: 13, text: "Forward Inference:", fill: "cyan" }),
          part({ type: "text", x: 165, y: 94, width: 280, height: 16, text: "ŷ = σ( W₂ · h + b )", fill: "white" }),
          part({ type: "rect", x: 12, y: 135, width: 306, height: 140, fill: "none", stroke: "green", strokeWidth: 1.5, opacity: 0.85 }),
          part({ type: "text", x: 165, y: 158, width: 280, height: 14, text: "Loss Function (MSE):", fill: "yellow" }),
          part({ type: "text", x: 165, y: 184, width: 280, height: 16, text: "L = ½ ( y - ŷ )²", fill: "yellow" }),
          part({ type: "text", x: 165, y: 218, width: 280, height: 13, text: "Backpropagation Gradient:", fill: "cyan" }),
          part({ type: "text", x: 165, y: 246, width: 280, height: 18, text: "ΔW = -η · ( ∂L / ∂W )", fill: "green" }),
          part({ type: "text", x: 165, y: 310, width: 280, height: 12, text: "η: learning rate  ·  σ: activation", fill: "slate" }),
        ],
      },
    ],
    connections: [
      { id: "conn-in-to-hidden", from: "nn-input-layer", to: "nn-hidden-layer", label: "weights W1", color: "violet", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
      { id: "conn-hidden-to-out", from: "nn-hidden-layer", to: "nn-output-layer", label: "weights W2", color: "green", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
      { id: "conn-out-to-loss", from: "nn-output-layer", to: "nn-formula-loss", label: "loss feedback", color: "yellow", route: "straight", fromAnchor: "right", toAnchor: "left", arrowhead: "arrow", bend: 0 },
    ],
    segments: [
      { id: "seg-nn-input", title: "Input Layer Features", targetIds: ["nn-input-layer"], action: "reveal", durationMs: 7500, narration: "At the input layer, numerical feature values x₁ through x₃ enter the neural network as input signals." },
      { id: "seg-nn-hidden", title: "Hidden Layer Processing", targetIds: ["nn-hidden-layer"], action: "focus", durationMs: 8500, narration: "These features flow across weighted connections into hidden neurons h₁ through h₄, where inputs are multiplied by weights W₁ and activated non-linearly." },
      { id: "seg-nn-output", title: "Output Layer Prediction", targetIds: ["nn-output-layer"], action: "trace", durationMs: 7500, narration: "The activated hidden representations combine across weights W₂ into the output layer to compute the network's prediction, y-hat." },
      { id: "seg-nn-loss-backprop", title: "Loss & Backpropagation", targetIds: ["nn-formula-loss"], action: "pulse", durationMs: 9500, narration: "Finally, the loss function evaluates error between prediction and true labels, and backpropagation calculates gradients to adjust weights by delta W, optimizing accuracy." },
    ],
  };
}
